# Generated by Django 2.0.2 on 2019-04-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
