# Generated by Django 2.0.2 on 2019-04-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20190421_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.IntegerField(max_length=5),
        ),
    ]
