# Generated by Django 2.0.2 on 2019-04-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20190421_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('answer', models.IntegerField()),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
            ],
        ),
    ]
