# Generated by Django 2.0.2 on 2019-04-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_trainingcards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingCards',
            new_name='TrainingCard',
        ),
    ]
